apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-ci-cd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-ci-cd
  template:
    metadata:
      labels:
        app: python-ci-cd
    spec:
      containers:
      - name: flask-app
        image: jibishwaran07/python-ci-cd-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
